# Generated by Django 5.1.7 on 2025-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_category', 'variation_value')},
        ),
    ]
