# Generated by Django 5.1.7 on 2025-04-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
